services:
    _defaults:
        public: false
    
    helpers_array.helpers_array:
        class: 'Jalismrs\HelpersArrayBundle\HelpersArray'
        arguments:
            $rateLimitProvider: '@Maba\GentleForce\RateLimitProvider'
            $throttler: '@Maba\GentleForce\ThrottlerInterface'
    
    Jalismrs\HelpersArrayBundle\HelpersArray: '@helpers_array.helpers_array'
    
    # maba/gentle-force
    Maba\GentleForce\RateLimitProvider:
        autowire: true
    Maba\GentleForce\Throttler:
        arguments:
            $client: '@Predis\Client'
            $rateLimitProvider: '@Maba\GentleForce\RateLimitProvider'
            $prefix: 'rate_limit::'
    Maba\GentleForce\ThrottlerInterface: '@Maba\GentleForce\Throttler'
    
    # predis/predis
    Predis\Client:
        arguments:
            $parameters:
                host: '%env(REDIS_HOST)%'
            $options:
                prefix: '%app.name%::'
